AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  add_book_prod

Globals:
  Function:
    Timeout: 10
    LoggingConfig:
      LogFormat: JSON

Parameters:
  CognitoUserPoolId:
    Type: String
    Description: The ID of the production Cognito User Pool
    Default: "eu-north-1_ncYQOqnAD"

Resources:
  AddBookApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"  # <-- Replace wildcard with actual domain
        MaxAge: "'600'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !Sub "arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${CognitoUserPoolId}"

  AddBookFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: add_book_prod/  # <-- Make sure your prod code is in this folder
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          SECRET_NAME: "NeonDatabaseUrlProd"
          REGION: "eu-north-1"
      Events:
        AddBook:
          Type: Api
          Properties:
            RestApiId: !Ref AddBookApi
            Path: /books
            Method: post
            Auth:
              Authorizer: CognitoAuthorizer
        AddBookOptions:
          Type: Api
          Properties:
            RestApiId: !Ref AddBookApi
            Path: /books
            Method: options
            Auth:
              Authorizer: NONE
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:NeonDatabaseUrlProd-*"

Outputs:
  AddBookApi:
    Description: API Gateway endpoint URL for Prod stage for Add Book function
    Value: !Sub "https://${AddBookApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books/"
  AddBookFunction:
    Description: Add Book Lambda Function ARN
    Value: !GetAtt AddBookFunction.Arn
  AddBookFunctionIamRole:
    Description: Implicit IAM Role created for Add Book function
    Value: !GetAtt AddBookFunctionRole.Arn
