version = 0.1
[default.deploy.parameters]
stack_name = "get-book-indexes-dev"
resolve_s3 = true
s3_prefix = "get-book-indexes-dev"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CognitoUserPoolId=\"eu-north-1_Cpr2QKIBI\""
image_repositories = []
